export default {
  allTags: [
    'Beginner',
    'Intermediate',
    'Expert',
    'DeFi',
    'GameFi',
    'SocialFi',
    'NFTs',
    'Scaling',
    'IPFS',
    'Arweave',
    'BNBChainPay',
    'Truffle',
    'OpenZeppelin',
    'Hardhat',
    'Band Protocol',
    'Gaming',
    'Governance',
    'Mobile',
    'Security',
    'Serum',
    'Metaplex',
    'Arweave',
    'BNBChainPay',
    'Anchor',
    'Web3.js',
    'MetaFi',
    'React.js',
    'Svelte',
    'Vue.js',
    'Rust',
    'JavaScript',
    'C#',
    'Golang',
    'Python',
    'Java',
    'Swift',
    'CLI',
    'Kotlin',
    'Dapp Development',
  ],
};
